export class HttpConstants {
	public HTTP_SUCCESS_OK = 200;
	public HTTP_CREATED = 201;
	public HTTP_NO_CONTENT = 204;
	public HTTP_BAD_REQUEST = 400;
	public HTTP_UNAUTHORIZED = 401;
	public HTTP_FORBIDDEN = 403;
	public HTTP_CONFLICT = 409;
	public HTTP_UNPROCESSABLE_ENTITY = 422;
	public HTTP_REQUESTED_RESOURCE_NOT_FOUND = 404;
	public HTTP_PRECONDITION_FAILED = 412;
	public HTTP_INTERNAL_SERVER_ERROR = 500;
}
